baseURL = "https://cpit251.github.io"
languageCode = "en-us"
title = "Software Engineering (I)"
theme = "course-site"
enableRobotsTXT = true
pygmentsCodeFences = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    anchorLineNos = true
    guessSyntax = false
    codeFences = true
[params]
  ghOrg = "cpit251"
  ghRepo = "cpit251.github.io"
